# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

default_stages:
  - pre-commit
  - pre-push

default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: go-generate
        name: go generate
        language: system
        entry: go generate ./...
        pass_filenames: false

      - id: cue-fmt
        name: cue format
        language: system
        entry: cue fmt
        types: [cue]
      - id: cue-vet
        name: cue vet
        language: system
        entry: cue vet -c
        types: [cue, yaml]
        pass_filenames: false

      - id: buf-fmt
        name: buf format
        language: system
        entry: go tool buf format
        types: [proto]
      - id: buf-lint
        name: buf lint
        language: system
        entry: go tool buf lint
        types: [proto]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --no-sort-keys

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.84.0
    hooks:
      - id: renovate-config-validator
        args: [--strict]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages:
          - commit-msg
          - manual

  - repo: https://github.com/korandoru/hawkeye
    rev: 77c2515a10d0133ea938118da962a2a2572cbf08
    hooks:
      - id: hawkeye-format-docker

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.4.0
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-full
      - id: golangci-lint-fmt
