// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: cuebe/v1/plugin.proto

package cuebev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigurePluginRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurePluginRequest) Reset() {
	*x = ConfigurePluginRequest{}
	mi := &file_cuebe_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePluginRequest) ProtoMessage() {}

func (x *ConfigurePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuebe_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigurePluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigurePluginRequest_builder) Build() *ConfigurePluginRequest {
	m0 := &ConfigurePluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigurePluginResponse struct {
	state               protoimpl.MessageState                                 `protogen:"opaque.v1"`
	xxx_hidden_Backends map[string]*ConfigurePluginResponse_BackendDescription `protobuf:"bytes,1,rep,name=backends" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigurePluginResponse) Reset() {
	*x = ConfigurePluginResponse{}
	mi := &file_cuebe_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePluginResponse) ProtoMessage() {}

func (x *ConfigurePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuebe_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurePluginResponse) GetBackends() map[string]*ConfigurePluginResponse_BackendDescription {
	if x != nil {
		return x.xxx_hidden_Backends
	}
	return nil
}

func (x *ConfigurePluginResponse) SetBackends(v map[string]*ConfigurePluginResponse_BackendDescription) {
	x.xxx_hidden_Backends = v
}

type ConfigurePluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Backends map[string]*ConfigurePluginResponse_BackendDescription
}

func (b0 ConfigurePluginResponse_builder) Build() *ConfigurePluginResponse {
	m0 := &ConfigurePluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Backends = b.Backends
	return m0
}

type PerformTaskRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Backend      *string                `protobuf:"bytes,1,opt,name=backend"`
	xxx_hidden_Inputs       []string               `protobuf:"bytes,2,rep,name=inputs"`
	xxx_hidden_Parameters   *structpb.Value        `protobuf:"bytes,3,opt,name=parameters"`
	xxx_hidden_OutDirectory *string                `protobuf:"bytes,4,opt,name=out_directory,json=outDirectory"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PerformTaskRequest) Reset() {
	*x = PerformTaskRequest{}
	mi := &file_cuebe_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformTaskRequest) ProtoMessage() {}

func (x *PerformTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuebe_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PerformTaskRequest) GetBackend() string {
	if x != nil {
		if x.xxx_hidden_Backend != nil {
			return *x.xxx_hidden_Backend
		}
		return ""
	}
	return ""
}

func (x *PerformTaskRequest) GetInputs() []string {
	if x != nil {
		return x.xxx_hidden_Inputs
	}
	return nil
}

func (x *PerformTaskRequest) GetParameters() *structpb.Value {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *PerformTaskRequest) GetOutDirectory() string {
	if x != nil {
		if x.xxx_hidden_OutDirectory != nil {
			return *x.xxx_hidden_OutDirectory
		}
		return ""
	}
	return ""
}

func (x *PerformTaskRequest) SetBackend(v string) {
	x.xxx_hidden_Backend = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *PerformTaskRequest) SetInputs(v []string) {
	x.xxx_hidden_Inputs = v
}

func (x *PerformTaskRequest) SetParameters(v *structpb.Value) {
	x.xxx_hidden_Parameters = v
}

func (x *PerformTaskRequest) SetOutDirectory(v string) {
	x.xxx_hidden_OutDirectory = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *PerformTaskRequest) HasBackend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PerformTaskRequest) HasParameters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parameters != nil
}

func (x *PerformTaskRequest) HasOutDirectory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PerformTaskRequest) ClearBackend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Backend = nil
}

func (x *PerformTaskRequest) ClearParameters() {
	x.xxx_hidden_Parameters = nil
}

func (x *PerformTaskRequest) ClearOutDirectory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OutDirectory = nil
}

type PerformTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Backend      *string
	Inputs       []string
	Parameters   *structpb.Value
	OutDirectory *string
}

func (b0 PerformTaskRequest_builder) Build() *PerformTaskRequest {
	m0 := &PerformTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Backend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Backend = b.Backend
	}
	x.xxx_hidden_Inputs = b.Inputs
	x.xxx_hidden_Parameters = b.Parameters
	if b.OutDirectory != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_OutDirectory = b.OutDirectory
	}
	return m0
}

type PerformTaskResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformTaskResponse) Reset() {
	*x = PerformTaskResponse{}
	mi := &file_cuebe_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformTaskResponse) ProtoMessage() {}

func (x *PerformTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuebe_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PerformTaskResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PerformTaskResponse_builder) Build() *PerformTaskResponse {
	m0 := &PerformTaskResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigurePluginResponse_BackendDescription struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Outputs []string               `protobuf:"bytes,1,rep,name=outputs"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigurePluginResponse_BackendDescription) Reset() {
	*x = ConfigurePluginResponse_BackendDescription{}
	mi := &file_cuebe_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurePluginResponse_BackendDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePluginResponse_BackendDescription) ProtoMessage() {}

func (x *ConfigurePluginResponse_BackendDescription) ProtoReflect() protoreflect.Message {
	mi := &file_cuebe_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurePluginResponse_BackendDescription) GetOutputs() []string {
	if x != nil {
		return x.xxx_hidden_Outputs
	}
	return nil
}

func (x *ConfigurePluginResponse_BackendDescription) SetOutputs(v []string) {
	x.xxx_hidden_Outputs = v
}

type ConfigurePluginResponse_BackendDescription_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Outputs []string
}

func (b0 ConfigurePluginResponse_BackendDescription_builder) Build() *ConfigurePluginResponse_BackendDescription {
	m0 := &ConfigurePluginResponse_BackendDescription{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Outputs = b.Outputs
	return m0
}

var File_cuebe_v1_plugin_proto protoreflect.FileDescriptor

const file_cuebe_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x15cuebe/v1/plugin.proto\x12\bcuebe.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x18\n" +
	"\x16ConfigurePluginRequest\"\x89\x02\n" +
	"\x17ConfigurePluginResponse\x12K\n" +
	"\bbackends\x18\x01 \x03(\v2/.cuebe.v1.ConfigurePluginResponse.BackendsEntryR\bbackends\x1a.\n" +
	"\x12BackendDescription\x12\x18\n" +
	"\aoutputs\x18\x01 \x03(\tR\aoutputs\x1aq\n" +
	"\rBackendsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.cuebe.v1.ConfigurePluginResponse.BackendDescriptionR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x12PerformTaskRequest\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x16\n" +
	"\x06inputs\x18\x02 \x03(\tR\x06inputs\x126\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"parameters\x12#\n" +
	"\rout_directory\x18\x04 \x01(\tR\foutDirectory\"\x15\n" +
	"\x13PerformTaskResponse2\xb8\x01\n" +
	"\x12CuebePluginService\x12V\n" +
	"\x0fConfigurePlugin\x12 .cuebe.v1.ConfigurePluginRequest\x1a!.cuebe.v1.ConfigurePluginResponse\x12J\n" +
	"\vPerformTask\x12\x1c.cuebe.v1.PerformTaskRequest\x1a\x1d.cuebe.v1.PerformTaskResponseB\x9c\x01\n" +
	"\fcom.cuebe.v1B\vPluginProtoP\x01Z9github.com/dislogical/cuebe/api/go/proto/cuebe/v1;cuebev1\xa2\x02\x03CXX\xaa\x02\bCuebe.V1\xca\x02\bCuebe\\V1\xe2\x02\x14Cuebe\\V1\\GPBMetadata\xea\x02\tCuebe::V1\x92\x03\x02\b\x01b\beditionsp\xe8\a"

var file_cuebe_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cuebe_v1_plugin_proto_goTypes = []any{
	(*ConfigurePluginRequest)(nil),                     // 0: cuebe.v1.ConfigurePluginRequest
	(*ConfigurePluginResponse)(nil),                    // 1: cuebe.v1.ConfigurePluginResponse
	(*PerformTaskRequest)(nil),                         // 2: cuebe.v1.PerformTaskRequest
	(*PerformTaskResponse)(nil),                        // 3: cuebe.v1.PerformTaskResponse
	(*ConfigurePluginResponse_BackendDescription)(nil), // 4: cuebe.v1.ConfigurePluginResponse.BackendDescription
	nil,                    // 5: cuebe.v1.ConfigurePluginResponse.BackendsEntry
	(*structpb.Value)(nil), // 6: google.protobuf.Value
}
var file_cuebe_v1_plugin_proto_depIdxs = []int32{
	5, // 0: cuebe.v1.ConfigurePluginResponse.backends:type_name -> cuebe.v1.ConfigurePluginResponse.BackendsEntry
	6, // 1: cuebe.v1.PerformTaskRequest.parameters:type_name -> google.protobuf.Value
	4, // 2: cuebe.v1.ConfigurePluginResponse.BackendsEntry.value:type_name -> cuebe.v1.ConfigurePluginResponse.BackendDescription
	0, // 3: cuebe.v1.CuebePluginService.ConfigurePlugin:input_type -> cuebe.v1.ConfigurePluginRequest
	2, // 4: cuebe.v1.CuebePluginService.PerformTask:input_type -> cuebe.v1.PerformTaskRequest
	1, // 5: cuebe.v1.CuebePluginService.ConfigurePlugin:output_type -> cuebe.v1.ConfigurePluginResponse
	3, // 6: cuebe.v1.CuebePluginService.PerformTask:output_type -> cuebe.v1.PerformTaskResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cuebe_v1_plugin_proto_init() }
func file_cuebe_v1_plugin_proto_init() {
	if File_cuebe_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cuebe_v1_plugin_proto_rawDesc), len(file_cuebe_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cuebe_v1_plugin_proto_goTypes,
		DependencyIndexes: file_cuebe_v1_plugin_proto_depIdxs,
		MessageInfos:      file_cuebe_v1_plugin_proto_msgTypes,
	}.Build()
	File_cuebe_v1_plugin_proto = out.File
	file_cuebe_v1_plugin_proto_goTypes = nil
	file_cuebe_v1_plugin_proto_depIdxs = nil
}
